all: fifo lru sec_chance

fifo: lab8stepFIFO.c
	gcc -o fifo lab8stepFIFO.c

lru: lab8stepLRU.c
	gcc -o lru lab8stepLRU.c

sec_chance: lab8step2CHANCE.c
	gcc -o sec_chance lab8step2CHANCE.c

clean:
	rm -f fifo lru sec_chance
