all: Step2 Step3 Step4 Step5

Step2: lab9step2.c
	gcc -o Step2 lab9step2.c

Step3: lab9step3.c
	gcc -o Step3 lab9step3.c

Step4: lab9step4.c
	gcc -o Step4 lab9step4.c

Step5: lab9step5.c
	gcc -o Step5 lab9step5.c -lpthread

clean:
	rm -f *.out Step2 Step3 Step4 Step5
